-- *==========================================*
-- *   CREATE SEQUENCES FOR H2                *
-- *==========================================*

create sequence if not exists wallet_id_seq;
create sequence if not exists param_gen_id_seq;
create sequence if not exists user_role_id_seq;
create sequence if not exists attribut_comp_option_values_id_seq;
create sequence if not exists mutuelle_indicatifs_autorises_id_seq;
create sequence if not exists attribut_comp_role_id_seq;
create sequence if not exists decoupage_geo_id_seq;
create sequence if not exists bureau_id_seq;
create sequence if not exists user_bureau_id_seq;
create sequence if not exists pays_id_seq;
create sequence if not exists periodicite_id_seq;
create sequence if not exists region_id_seq;
create sequence if not exists mutuelle_id_seq;
create sequence if not exists parametres_divers_id_seq;
create sequence if not exists type_information_id_seq;
create sequence if not exists attribut_comp_id_seq;
create sequence if not exists departement_id_seq;
create sequence if not exists niveau_decoupage_geo_id_seq;
create sequence if not exists credit_erreur_remb_id_seq;
create sequence if not exists garantie_id_seq;
create sequence if not exists garantie_assurance_id_seq;
create sequence if not exists reechelonnement_id_seq;
create sequence if not exists creance_rattachee_id_seq;
create sequence if not exists credit_compte_id_seq;
create sequence if not exists tableau_amortissement_fond_gar_id_seq;
create sequence if not exists credit_dynamic_form_id_seq;
create sequence if not exists garantie_avoir_id_seq;
create sequence if not exists tableau_amortissement_inventaire_id_seq;
create sequence if not exists credit_id_seq;
create sequence if not exists memo_credit_id_seq;
create sequence if not exists credit_inventaire_id_seq;
create sequence if not exists tableau_amortissement_id_seq;
create sequence if not exists garantie_bien_id_seq;
create sequence if not exists tableau_amortissement_tmp_id_seq;
create sequence if not exists tableau_amortissement_fond_gar_id_seq;
create sequence if not exists client_souscription_frais_fonds_garantie_id_seq;
create sequence if not exists provision_pret_id_seq;
create sequence if not exists choix_id_seq;
create sequence if not exists report_id_seq;
create sequence if not exists sub_report_id_seq;
create sequence if not exists report_parameter_value_id_seq;
create sequence if not exists report_categorie_id_seq;
create sequence if not exists report_copy_id_seq;
create sequence if not exists report_parameter_id_seq;
create sequence if not exists attribut_client_id_seq;
create sequence if not exists civilite_id_seq;
create sequence if not exists genre_client_id_seq;
create sequence if not exists agent_credit_id_seq;
create sequence if not exists fonction_uo_id_seq;
create sequence if not exists attribut_genre_client_id_seq;
create sequence if not exists nature_piece_id_seq;
create sequence if not exists employeur_id_seq;
create sequence if not exists critere_unicite_client_id_seq;
create sequence if not exists qualite_client_id_seq;
create sequence if not exists profession_id_seq;
create sequence if not exists fonction_membre_id_seq;
create sequence if not exists unite_organisation_id_seq;
create sequence if not exists activite_client_id_seq;
create sequence if not exists type_client_id_seq;
create sequence if not exists statut_juridique_id_seq;
create sequence if not exists sous_activite_client_id_seq;
create sequence if not exists type_adresse_id_seq;
create sequence if not exists attribut_complementaire_id_seq;
create sequence if not exists interet_epargne_id_seq;
create sequence if not exists avance_dat_id_seq;
create sequence if not exists depot_terme_id_seq;
create sequence if not exists security_param_id_seq;
create sequence if not exists module_id_seq;
create sequence if not exists menu_map_id_seq;
create sequence if not exists jwt_info_id_seq;
create sequence if not exists password_backup_id_seq;
create sequence if not exists requestmap_id_seq;
create sequence if not exists user_last_activity_id_seq;
create sequence if not exists app_partner_id_seq;
create sequence if not exists utilisateur_id_seq;
create sequence if not exists security_parameter_id_seq;
create sequence if not exists log_activity_id_seq;
create sequence if not exists audit_log_id_seq;
create sequence if not exists security_event_id_seq;
create sequence if not exists role_id_seq;
create sequence if not exists log_batch_id_seq;
create sequence if not exists ecriture_cg_id_seq;
create sequence if not exists compte_general_id_seq;
create sequence if not exists traitement_batch_id_seq;
create sequence if not exists balance_ca_tmp_id_seq;
create sequence if not exists balance_tmp_id_seq;
create sequence if not exists chapitre_comptable_arrete_id_seq;
create sequence if not exists ecriture_id_seq;
create sequence if not exists acquisition_immo_id_seq;
create sequence if not exists billetage_operation_id_seq;
create sequence if not exists balance_cg_tmp_id_seq;
create sequence if not exists operation_id_seq;
create sequence if not exists date_traitement_id_seq;
create sequence if not exists fichier_excel_id_seq;
create sequence if not exists montant_en_opposition_id_seq;
create sequence if not exists traitement_excel_tmp_id_seq;
create sequence if not exists extourne_tmp_id_seq;
create sequence if not exists document_id_seq;
create sequence if not exists budget_id_seq;
create sequence if not exists billetage_caisse_id_seq;
create sequence if not exists echelle_interet_details_id_seq;
create sequence if not exists traitement_excel_id_seq;
create sequence if not exists compte_id_seq;
create sequence if not exists historique_operation_complementaire_id_seq;
create sequence if not exists calcul_immo_id_seq;
create sequence if not exists echelle_interet_id_seq;
create sequence if not exists historique_operation_id_seq;
create sequence if not exists extourne_op_masse_erreur_id_seq;
create sequence if not exists historique_ecriture_id_seq;
create sequence if not exists numero_operation_id_seq;
create sequence if not exists solde_arrete_cg_id_seq;
create sequence if not exists amortissement_immo_id_seq;
create sequence if not exists solde_arrete_id_seq;
create sequence if not exists numero_lot_genere_id_seq;
create sequence if not exists operation_complementaire_id_seq;
create sequence if not exists virement_permanent_id_seq;
create sequence if not exists immobilisation_id_seq;
create sequence if not exists entite_attribut_comp_id_seq;
create sequence if not exists reprise_credit_id_seq;
create sequence if not exists reprise_depot_terme_id_seq;
create sequence if not exists client_tmp_id_seq;
create sequence if not exists reprise_compte_id_seq;
create sequence if not exists reprise_erreur_id_seq;
create sequence if not exists reprise_journal_operation_id_seq;
create sequence if not exists forms_field_id_seq;
create sequence if not exists dynamic_field_id_seq;
create sequence if not exists formulaire_saisie_id_seq;
create sequence if not exists dynamic_form_id_seq;
create sequence if not exists select_choice_id_seq;
create sequence if not exists taux_penalite_tranche_id_seq;
create sequence if not exists type_epargne_terme_id_seq;
create sequence if not exists aster_operation_id_seq;
create sequence if not exists aster_client_id_seq;
create sequence if not exists collecte_journal_id_seq;
create sequence if not exists collecte_epargne_id_seq;
create sequence if not exists tontine_cycle_mise_id_seq;
create sequence if not exists tontine_zone_id_seq;
create sequence if not exists tontine_adhesion_mise_id_seq;
create sequence if not exists collecte_journal_details_id_seq;
create sequence if not exists tontine_cycle_id_seq;
create sequence if not exists tontine_id_seq;
create sequence if not exists tontine_adhesion_id_seq;
create sequence if not exists version_db_id_seq;
create sequence if not exists version_db_script_id_seq;
create sequence if not exists caisse_id_seq;
create sequence if not exists schema_ecriture_id_seq;
create sequence if not exists evenements_comptable_chapitre_comptable_autorise_id_seq;
create sequence if not exists schemas_comptable_id_seq;
create sequence if not exists taux_devise_historique_id_seq;
create sequence if not exists frais_type_compte_cond_genre_id_seq;
create sequence if not exists type_collecte_id_seq;
create sequence if not exists motif_cloture_compte_id_seq;
create sequence if not exists libelle_operation_id_seq;
create sequence if not exists type_immobilisation_id_seq;
create sequence if not exists frais_type_compte_cond_client_id_seq;
create sequence if not exists type_blocage_compte_id_seq;
create sequence if not exists type_billet_id_seq;
create sequence if not exists evenements_comptable_id_seq;
create sequence if not exists type_operation_banalisee_id_seq;
create sequence if not exists programme_batch_id_seq;
create sequence if not exists frais_type_collecte_id_seq;
create sequence if not exists chapitre_comptable_id_seq;
create sequence if not exists comptes_mouvement_operation_banalisee_id_seq;
create sequence if not exists type_compte_chapitre_id_seq;
create sequence if not exists poste_budgetaire_id_seq;
create sequence if not exists compte_retrait_interne_id_seq;
create sequence if not exists frais_pallier_id_seq;
create sequence if not exists user_chapitre_comptable_autorise_id_seq;
create sequence if not exists taux_interet_tranche_id_seq;
create sequence if not exists tag_ecriture_id_seq;
create sequence if not exists compte_genere_id_seq;
create sequence if not exists type_transaction_caisse_id_seq;
create sequence if not exists taux_devise_id_seq;
create sequence if not exists banque_id_seq;
create sequence if not exists frais_type_compte_id_seq;
create sequence if not exists date_arrete_id_seq;
create sequence if not exists frais_id_seq;
create sequence if not exists op_diverse_autorisee_id_seq;
create sequence if not exists devise_id_seq;
create sequence if not exists type_compte_id_seq;
create sequence if not exists sms_service_abonnement_id_seq;
create sequence if not exists service_sms_sms_action_appels_id_seq;
create sequence if not exists msg_template_id_seq;
create sequence if not exists service_sms_id_seq;
create sequence if not exists com_message_id_seq;
create sequence if not exists sms_action_appel_id_seq;
create sequence if not exists poste_etat_financier_chapitre_id_seq;
create sequence if not exists poste_etat_financier_id_seq;
create sequence if not exists poste_etat_financier_arrete_id_seq;
create sequence if not exists tmp_val_poste_etat_financier_arrete_id_seq;
create sequence if not exists poste_etat_financier_interne_id_seq;
create sequence if not exists mandataire_id_seq;
create sequence if not exists personne_morale_id_seq;
create sequence if not exists personne_physique_id_seq;
create sequence if not exists membre_uo_complement_id_seq;
create sequence if not exists adresse_id_seq;
create sequence if not exists membre_uo_id_seq;
create sequence if not exists client_id_seq;
create sequence if not exists groupe_solidarite_id_seq;
create sequence if not exists elements_id_seq;
create sequence if not exists employeur_id_seq;
create sequence if not exists frais_client_id_seq;
create sequence if not exists groupe_solidarite_historique_transfert_id_seq;
create sequence if not exists mandataire_compte_id_seq;
create sequence if not exists domiciliation_salaire_id_seq;
create sequence if not exists actionnaire_id_seq;
create sequence if not exists membre_groupement_id_seq;
create sequence if not exists unite_organisation_id_seq;
create sequence if not exists tiers_id_seq;
create sequence if not exists jasper_gw_param_id_seq;
create sequence if not exists jasper_report_unit_resource_role_id_seq;
create sequence if not exists jasper_report_unit_resource_id_seq;
create sequence if not exists tranche_montant_credit_id_seq;
create sequence if not exists type_memo_credit_id_seq;
create sequence if not exists dynamic_form_type_pret_id_seq;
create sequence if not exists taux_epargne_type_pret_id_seq;
create sequence if not exists taux_epargne_type_pret_cond_client_id_seq;
create sequence if not exists taux_epargne_type_pret_cond_genre_id_seq;
create sequence if not exists etape_credit_id_seq;
create sequence if not exists programme_credit_id_seq;
create sequence if not exists frais_type_pret_cond_client_id_seq;
create sequence if not exists frais_type_pret_id_seq;
create sequence if not exists frais_type_pret_cond_genre_id_seq;
create sequence if not exists detail_activite_type_pret_id_seq;
create sequence if not exists nature_bien_id_seq;
create sequence if not exists compte_type_pret_id_seq;
create sequence if not exists qualite_bien_id_seq;
create sequence if not exists taux_provision_id_seq;
create sequence if not exists type_pret_id_seq;
create sequence if not exists sql_request_id_seq;
create sequence if not exists tranche_de_revenu_id_seq;
create sequence if not exists capacite_juridique_id_seq;
create sequence if not exists regime_matrimoniale_id_seq;
create sequence if not exists situation_matrimoniale_id_seq;
-- reset des sequences
-- alter sequence user_role_id_seq restart with (select coalesce(max(id),0) +1 from user_role);
alter sequence wallet_id_seq restart with (select coalesce(max(id),0) +1 from wallet);
alter sequence param_gen_id_seq restart with (select coalesce(max(id),0) +1 from param_gen);
alter sequence attribut_comp_option_values_id_seq restart with (select coalesce(max(id),0) +1 from attribut_comp_option_values);
alter sequence mutuelle_indicatifs_autorises_id_seq restart with (select coalesce(max(id),0) +1 from mutuelle_indicatifs_autorises);
alter sequence attribut_comp_role_id_seq restart with (select coalesce(max(id),0) +1 from attribut_comp_role);
alter sequence decoupage_geo_id_seq restart with (select coalesce(max(id),0) +1 from decoupage_geo);
alter sequence bureau_id_seq restart with (select coalesce(max(id),0) +1 from bureau);
-- alter sequence user_bureau_id_seq restart with (select coalesce(max(id),0) +1 from user_bureau);
alter sequence pays_id_seq restart with (select coalesce(max(id),0) +1 from pays);
alter sequence periodicite_id_seq restart with (select coalesce(max(id),0) +1 from periodicite);
alter sequence region_id_seq restart with (select coalesce(max(id),0) +1 from region);
alter sequence mutuelle_id_seq restart with (select coalesce(max(id),0) +1 from mutuelle);
alter sequence parametres_divers_id_seq restart with (select coalesce(max(id),0) +1 from parametres_divers);
alter sequence type_information_id_seq restart with (select coalesce(max(id),0) +1 from type_information);
alter sequence attribut_comp_id_seq restart with (select coalesce(max(id),0) +1 from attribut_comp);
alter sequence departement_id_seq restart with (select coalesce(max(id),0) +1 from departement);
alter sequence niveau_decoupage_geo_id_seq restart with (select coalesce(max(id),0) +1 from niveau_decoupage_geo);
alter sequence credit_erreur_remb_id_seq restart with (select coalesce(max(id),0) +1 from credit_erreur_remb);
alter sequence garantie_id_seq restart with (select coalesce(max(id),0) +1 from garantie);
alter sequence garantie_assurance_id_seq restart with (select coalesce(max(id),0) +1 from garantie_assurance);
alter sequence reechelonnement_id_seq restart with (select coalesce(max(id),0) +1 from reechelonnement);
alter sequence creance_rattachee_id_seq restart with (select coalesce(max(id),0) +1 from creance_rattachee);
alter sequence credit_compte_id_seq restart with (select coalesce(max(id),0) +1 from credit_compte);
alter sequence tableau_amortissement_fond_gar_id_seq restart with (select coalesce(max(id),0) +1 from tableau_amortissement_fond_gar);
alter sequence credit_dynamic_form_id_seq restart with (select coalesce(max(id),0) +1 from credit_dynamic_form);
alter sequence garantie_avoir_id_seq restart with (select coalesce(max(id),0) +1 from garantie_avoir);
alter sequence tableau_amortissement_inventaire_id_seq restart with (select coalesce(max(id),0) +1 from tableau_amortissement_inventaire);
alter sequence credit_id_seq restart with (select coalesce(max(id),0) +1 from credit);
alter sequence memo_credit_id_seq restart with (select coalesce(max(id),0) +1 from memo_credit);
alter sequence credit_inventaire_id_seq restart with (select coalesce(max(id),0) +1 from credit_inventaire);
alter sequence tableau_amortissement_id_seq restart with (select coalesce(max(id),0) +1 from tableau_amortissement);
alter sequence garantie_bien_id_seq restart with (select coalesce(max(id),0) +1 from garantie_bien);
alter sequence tableau_amortissement_tmp_id_seq restart with (select coalesce(max(id),0) +1 from tableau_amortissement_tmp);
alter sequence tableau_amortissement_fond_gar_id_seq restart with (select coalesce(max(id),0) +1 from tableau_amortissement_fond_gar);
alter sequence client_souscription_frais_fonds_garantie_id_seq restart with (select coalesce(max(id),0) +1 from client_souscription_frais_fonds_garantie);
alter sequence provision_pret_id_seq restart with (select coalesce(max(id),0) +1 from provision_pret);
alter sequence choix_id_seq restart with (select coalesce(max(id),0) +1 from choix);
alter sequence report_id_seq restart with (select coalesce(max(id),0) +1 from report);
alter sequence sub_report_id_seq restart with (select coalesce(max(id),0) +1 from sub_report);
alter sequence report_parameter_value_id_seq restart with (select coalesce(max(id),0) +1 from report_parameter_value);
alter sequence report_categorie_id_seq restart with (select coalesce(max(id),0) +1 from report_categorie);
alter sequence report_copy_id_seq restart with (select coalesce(max(id),0) +1 from report_copy);
alter sequence report_parameter_id_seq restart with (select coalesce(max(id),0) +1 from report_parameter);
alter sequence attribut_client_id_seq restart with (select coalesce(max(id),0) +1 from attribut_client);
alter sequence civilite_id_seq restart with (select coalesce(max(id),0) +1 from civilite);
alter sequence genre_client_id_seq restart with (select coalesce(max(id),0) +1 from genre_client);
alter sequence agent_credit_id_seq restart with (select coalesce(max(id),0) +1 from agent_credit);
alter sequence fonction_uo_id_seq restart with (select coalesce(max(id),0) +1 from fonctionuo);
alter sequence attribut_genre_client_id_seq restart with (select coalesce(max(id),0) +1 from attribut_genre_client);
alter sequence nature_piece_id_seq restart with (select coalesce(max(id),0) +1 from nature_piece);
alter sequence employeur_id_seq restart with (select coalesce(max(id),0) +1 from employeur);
alter sequence critere_unicite_client_id_seq restart with (select coalesce(max(id),0) +1 from critere_unicite_client);
alter sequence qualite_client_id_seq restart with (select coalesce(max(id),0) +1 from qualite_client);
alter sequence profession_id_seq restart with (select coalesce(max(id),0) +1 from profession);
alter sequence fonction_membre_id_seq restart with (select coalesce(max(id),0) +1 from fonction_membre);
alter sequence unite_organisation_id_seq restart with (select coalesce(max(id),0) +1 from unite_organisation);
alter sequence activite_client_id_seq restart with (select coalesce(max(id),0) +1 from activite_client);
alter sequence type_client_id_seq restart with (select coalesce(max(id),0) +1 from type_client);
alter sequence statut_juridique_id_seq restart with (select coalesce(max(id),0) +1 from statut_juridique);
alter sequence sous_activite_client_id_seq restart with (select coalesce(max(id),0) +1 from sous_activite_client);
alter sequence type_adresse_id_seq restart with (select coalesce(max(id),0) +1 from type_adresse);
alter sequence attribut_complementaire_id_seq restart with (select coalesce(max(id),0) +1 from attribut_complementaire);
alter sequence interet_epargne_id_seq restart with (select coalesce(max(id),0) +1 from interet_epargne);
alter sequence avance_dat_id_seq restart with (select coalesce(max(id),0) +1 from avance_dat);
alter sequence depot_terme_id_seq restart with (select coalesce(max(id),0) +1 from depot_terme);
alter sequence security_param_id_seq restart with (select coalesce(max(id),0) +1 from security_param);
alter sequence module_id_seq restart with (select coalesce(max(id),0) +1 from module);
alter sequence menu_map_id_seq restart with (select coalesce(max(id),0) +1 from menu_map);
alter sequence jwt_info_id_seq restart with (select coalesce(max(id),0) +1 from jwt_info);
alter sequence password_backup_id_seq restart with (select coalesce(max(id),0) +1 from password_backup);
alter sequence requestmap_id_seq restart with (select coalesce(max(id),0) +1 from requestmap);
alter sequence user_last_activity_id_seq restart with (select coalesce(max(id),0) +1 from user_last_activity);
alter sequence app_partner_id_seq restart with (select coalesce(max(id),0) +1 from app_partner);
alter sequence utilisateur_id_seq restart with (select coalesce(max(id),0) +1 from utilisateur);
alter sequence security_parameter_id_seq restart with (select coalesce(max(id),0) +1 from security_parameter);
alter sequence log_activity_id_seq restart with (select coalesce(max(id),0) +1 from log_activity);
alter sequence audit_log_id_seq restart with (select coalesce(max(id),0) +1 from audit_log);
alter sequence security_event_id_seq restart with (select coalesce(max(id),0) +1 from security_event);
alter sequence role_id_seq restart with (select coalesce(max(id),0) +1 from role);
alter sequence log_batch_id_seq restart with (select coalesce(max(id),0) +1 from log_batch);
alter sequence ecriture_cg_id_seq restart with (select coalesce(max(id),0) +1 from ecriture_cg);
alter sequence compte_general_id_seq restart with (select coalesce(max(id),0) +1 from compte_general);
alter sequence traitement_batch_id_seq restart with (select coalesce(max(id),0) +1 from traitement_batch);
alter sequence balance_ca_tmp_id_seq restart with (select coalesce(max(id),0) +1 from balance_ca_tmp);
alter sequence balance_tmp_id_seq restart with (select coalesce(max(id),0) +1 from balance_tmp);
alter sequence chapitre_comptable_arrete_id_seq restart with (select coalesce(max(id),0) +1 from chapitre_comptable_arrete);
alter sequence ecriture_id_seq restart with (select coalesce(max(id),0) +1 from ecriture);
alter sequence acquisition_immo_id_seq restart with (select coalesce(max(id),0) +1 from acquisition_immo);
alter sequence billetage_operation_id_seq restart with (select coalesce(max(id),0) +1 from billetage_operation);
alter sequence balance_cg_tmp_id_seq restart with (select coalesce(max(id),0) +1 from balance_cg_tmp);
alter sequence operation_id_seq restart with (select coalesce(max(id),0) +1 from operation);
alter sequence date_traitement_id_seq restart with (select coalesce(max(id),0) +1 from date_traitement);
alter sequence fichier_excel_id_seq restart with (select coalesce(max(id),0) +1 from fichier_excel);
alter sequence montant_en_opposition_id_seq restart with (select coalesce(max(id),0) +1 from montant_en_opposition);
alter sequence traitement_excel_tmp_id_seq restart with (select coalesce(max(id),0) +1 from traitement_excel_tmp);
alter sequence extourne_tmp_id_seq restart with (select coalesce(max(id),0) +1 from extourne_tmp);
alter sequence document_id_seq restart with (select coalesce(max(id),0) +1 from document);
alter sequence budget_id_seq restart with (select coalesce(max(id),0) +1 from budget);
alter sequence billetage_caisse_id_seq restart with (select coalesce(max(id),0) +1 from billetage_caisse);
alter sequence echelle_interet_details_id_seq restart with (select coalesce(max(id),0) +1 from echelle_interet_details);
alter sequence traitement_excel_id_seq restart with (select coalesce(max(id),0) +1 from traitement_excel);
alter sequence compte_id_seq restart with (select coalesce(max(id),0) +1 from compte);
alter sequence historique_operation_complementaire_id_seq restart with (select coalesce(max(id),0) +1 from historique_operation_complementaire);
alter sequence calcul_immo_id_seq restart with (select coalesce(max(id),0) +1 from calcul_immo);
alter sequence echelle_interet_id_seq restart with (select coalesce(max(id),0) +1 from echelle_interet);
alter sequence historique_operation_id_seq restart with (select coalesce(max(id),0) +1 from historique_operation);
alter sequence extourne_op_masse_erreur_id_seq restart with (select coalesce(max(id),0) +1 from extourne_op_masse_erreur);
alter sequence historique_ecriture_id_seq restart with (select coalesce(max(id),0) +1 from historique_ecriture);
alter sequence numero_operation_id_seq restart with (select coalesce(max(id),0) +1 from numero_operation);
alter sequence solde_arrete_cg_id_seq restart with (select coalesce(max(id),0) +1 from solde_arrete_cg);
alter sequence amortissement_immo_id_seq restart with (select coalesce(max(id),0) +1 from amortissement_immo);
alter sequence solde_arrete_id_seq restart with (select coalesce(max(id),0) +1 from solde_arrete);
alter sequence numero_lot_genere_id_seq restart with (select coalesce(max(id),0) +1 from numero_lot_genere);
alter sequence operation_complementaire_id_seq restart with (select coalesce(max(id),0) +1 from operation_complementaire);
alter sequence virement_permanent_id_seq restart with (select coalesce(max(id),0) +1 from virement_permanent);
alter sequence immobilisation_id_seq restart with (select coalesce(max(id),0) +1 from immobilisation);
alter sequence entite_attribut_comp_id_seq restart with (select coalesce(max(id),0) +1 from entite_attribut_comp);
alter sequence reprise_credit_id_seq restart with (select coalesce(max(id),0) +1 from reprise_credit);
alter sequence reprise_depot_terme_id_seq restart with (select coalesce(max(id),0) +1 from reprise_depot_terme);
alter sequence client_tmp_id_seq restart with (select coalesce(max(id),0) +1 from client_tmp);
alter sequence reprise_compte_id_seq restart with (select coalesce(max(id),0) +1 from reprise_compte);
alter sequence reprise_erreur_id_seq restart with (select coalesce(max(id),0) +1 from reprise_erreur);
alter sequence reprise_journal_operation_id_seq restart with (select coalesce(max(id),0) +1 from reprise_journal_operation);
alter sequence forms_field_id_seq restart with (select coalesce(max(id),0) +1 from forms_field);
alter sequence dynamic_field_id_seq restart with (select coalesce(max(id),0) +1 from dynamic_field);
alter sequence formulaire_saisie_id_seq restart with (select coalesce(max(id),0) +1 from formulaire_saisie);
alter sequence dynamic_form_id_seq restart with (select coalesce(max(id),0) +1 from dynamic_form);
alter sequence select_choice_id_seq restart with (select coalesce(max(id),0) +1 from select_choice);
alter sequence taux_penalite_tranche_id_seq restart with (select coalesce(max(id),0) +1 from taux_penalite_tranche);
alter sequence type_epargne_terme_id_seq restart with (select coalesce(max(id),0) +1 from type_epargne_terme);
alter sequence aster_operation_id_seq restart with (select coalesce(max(id),0) +1 from aster_operation);
alter sequence aster_client_id_seq restart with (select coalesce(max(id),0) +1 from aster_client);
alter sequence collecte_journal_id_seq restart with (select coalesce(max(id),0) +1 from collecte_journal);
alter sequence collecte_epargne_id_seq restart with (select coalesce(max(id),0) +1 from collecte_epargne);
alter sequence tontine_cycle_mise_id_seq restart with (select coalesce(max(id),0) +1 from tontine_cycle_mise);
alter sequence tontine_zone_id_seq restart with (select coalesce(max(id),0) +1 from tontine_zone);
alter sequence tontine_adhesion_mise_id_seq restart with (select coalesce(max(id),0) +1 from tontine_adhesion_mise);
alter sequence collecte_journal_details_id_seq restart with (select coalesce(max(id),0) +1 from collecte_journal_details);
alter sequence tontine_cycle_id_seq restart with (select coalesce(max(id),0) +1 from tontine_cycle);
alter sequence tontine_id_seq restart with (select coalesce(max(id),0) +1 from tontine);
alter sequence tontine_adhesion_id_seq restart with (select coalesce(max(id),0) +1 from tontine_adhesion);
alter sequence version_db_id_seq restart with (select coalesce(max(id),0) +1 from version_db);
alter sequence version_db_script_id_seq restart with (select coalesce(max(id),0) +1 from version_db_script);
alter sequence caisse_id_seq restart with (select coalesce(max(id),0) +1 from caisse);
alter sequence schema_ecriture_id_seq restart with (select coalesce(max(id),0) +1 from schema_ecriture);
alter sequence evenements_comptable_chapitre_comptable_autorise_id_seq restart with (select coalesce(max(id),0) +1 from evenements_comptable_chapitre_comptable_autorise);
alter sequence schemas_comptable_id_seq restart with (select coalesce(max(id),0) +1 from schemas_comptable);
alter sequence taux_devise_historique_id_seq restart with (select coalesce(max(id),0) +1 from taux_devise_historique);
alter sequence frais_type_compte_cond_genre_id_seq restart with (select coalesce(max(id),0) +1 from frais_type_compte_cond_genre);
alter sequence type_collecte_id_seq restart with (select coalesce(max(id),0) +1 from type_collecte);
alter sequence motif_cloture_compte_id_seq restart with (select coalesce(max(id),0) +1 from motif_cloture_compte);
alter sequence libelle_operation_id_seq restart with (select coalesce(max(id),0) +1 from libelle_operation);
alter sequence type_immobilisation_id_seq restart with (select coalesce(max(id),0) +1 from type_immobilisation);
alter sequence frais_type_compte_cond_client_id_seq restart with (select coalesce(max(id),0) +1 from frais_type_compte_cond_client);
alter sequence type_blocage_compte_id_seq restart with (select coalesce(max(id),0) +1 from type_blocage_compte);
alter sequence type_billet_id_seq restart with (select coalesce(max(id),0) +1 from type_billet);
alter sequence evenements_comptable_id_seq restart with (select coalesce(max(id),0) +1 from evenements_comptable);
alter sequence type_operation_banalisee_id_seq restart with (select coalesce(max(id),0) +1 from type_operation_banalisee);
alter sequence programme_batch_id_seq restart with (select coalesce(max(id),0) +1 from programme_batch);
alter sequence frais_type_collecte_id_seq restart with (select coalesce(max(id),0) +1 from frais_type_collecte);
alter sequence chapitre_comptable_id_seq restart with (select coalesce(max(id),0) +1 from chapitre_comptable);
alter sequence comptes_mouvement_operation_banalisee_id_seq restart with (select coalesce(max(id),0) +1 from comptes_mouvement_operation_banalisee);
alter sequence type_compte_chapitre_id_seq restart with (select coalesce(max(id),0) +1 from type_compte_chapitre);
alter sequence poste_budgetaire_id_seq restart with (select coalesce(max(id),0) +1 from poste_budgetaire);
alter sequence compte_retrait_interne_id_seq restart with (select coalesce(max(id),0) +1 from compte_retrait_interne);
alter sequence frais_pallier_id_seq restart with (select coalesce(max(id),0) +1 from frais_pallier);
alter sequence user_chapitre_comptable_autorise_id_seq restart with (select coalesce(max(id),0) +1 from user_chapitre_comptable_autorise);
alter sequence taux_interet_tranche_id_seq restart with (select coalesce(max(id),0) +1 from taux_interet_tranche);
alter sequence tag_ecriture_id_seq restart with (select coalesce(max(id),0) +1 from tag_ecriture);
alter sequence compte_genere_id_seq restart with (select coalesce(max(id),0) +1 from compte_genere);
alter sequence type_transaction_caisse_id_seq restart with (select coalesce(max(id),0) +1 from type_transaction_caisse);
alter sequence taux_devise_id_seq restart with (select coalesce(max(id),0) +1 from taux_devise);
alter sequence banque_id_seq restart with (select coalesce(max(id),0) +1 from banque);
alter sequence frais_type_compte_id_seq restart with (select coalesce(max(id),0) +1 from frais_type_compte);
alter sequence date_arrete_id_seq restart with (select coalesce(max(id),0) +1 from date_arrete);
alter sequence frais_id_seq restart with (select coalesce(max(id),0) +1 from frais);
alter sequence op_diverse_autorisee_id_seq restart with (select coalesce(max(id),0) +1 from op_diverse_autorisee);
alter sequence devise_id_seq restart with (select coalesce(max(id),0) +1 from devise);
alter sequence type_compte_id_seq restart with (select coalesce(max(id),0) +1 from type_compte);
alter sequence sms_service_abonnement_id_seq restart with (select coalesce(max(id),0) +1 from sms_service_abonnement);
alter sequence service_sms_sms_action_appels_id_seq restart with (select coalesce(max(id),0) +1 from service_sms_sms_action_appels);
alter sequence msg_template_id_seq restart with (select coalesce(max(id),0) +1 from msg_template);
alter sequence service_sms_id_seq restart with (select coalesce(max(id),0) +1 from service_sms);
alter sequence com_message_id_seq restart with (select coalesce(max(id),0) +1 from com_message);
alter sequence sms_action_appel_id_seq restart with (select coalesce(max(id),0) +1 from sms_action_appel);
alter sequence poste_etat_financier_chapitre_id_seq restart with (select coalesce(max(id),0) +1 from poste_etat_financier_chapitre);
alter sequence poste_etat_financier_id_seq restart with (select coalesce(max(id),0) +1 from poste_etat_financier);
alter sequence poste_etat_financier_arrete_id_seq restart with (select coalesce(max(id),0) +1 from poste_etat_financier_arrete);
alter sequence tmp_val_poste_etat_financier_arrete_id_seq restart with (select coalesce(max(id),0) +1 from tmp_val_poste_etat_financier_arrete);
alter sequence poste_etat_financier_interne_id_seq restart with (select coalesce(max(id),0) +1 from poste_etat_financier_interne);
alter sequence mandataire_id_seq restart with (select coalesce(max(id),0) +1 from mandataire);
alter sequence personne_morale_id_seq restart with (select coalesce(max(id),0) +1 from personne_morale);
alter sequence personne_physique_id_seq restart with (select coalesce(max(id),0) +1 from personne_physique);
alter sequence membre_uo_complement_id_seq restart with (select coalesce(max(id),0) +1 from membreuocomplement);
alter sequence adresse_id_seq restart with (select coalesce(max(id),0) +1 from adresse);
alter sequence membre_uo_id_seq restart with (select coalesce(max(id),0) +1 from membreuo);
alter sequence client_id_seq restart with (select coalesce(max(id),0) +1 from client);
alter sequence groupe_solidarite_id_seq restart with (select coalesce(max(id),0) +1 from groupe_solidarite);
alter sequence elements_id_seq restart with (select coalesce(max(id),0) +1 from elements);
alter sequence employeur_id_seq restart with (select coalesce(max(id),0) +1 from employeur);
alter sequence frais_client_id_seq restart with (select coalesce(max(id),0) +1 from frais_client);
alter sequence groupe_solidarite_historique_transfert_id_seq restart with (select coalesce(max(id),0) +1 from groupe_solidarite_historique_transfert);
alter sequence mandataire_compte_id_seq restart with (select coalesce(max(id),0) +1 from mandataire_compte);
alter sequence domiciliation_salaire_id_seq restart with (select coalesce(max(id),0) +1 from domiciliation_salaire);
alter sequence actionnaire_id_seq restart with (select coalesce(max(id),0) +1 from actionnaire);
alter sequence membre_groupement_id_seq restart with (select coalesce(max(id),0) +1 from membre_groupement);
alter sequence unite_organisation_id_seq restart with (select coalesce(max(id),0) +1 from unite_organisation);
alter sequence tiers_id_seq restart with (select coalesce(max(id),0) +1 from tiers);
alter sequence jasper_gw_param_id_seq restart with (select coalesce(max(id),0) +1 from jasper_gw_param);
alter sequence jasper_report_unit_resource_role_id_seq restart with (select coalesce(max(id),0) +1 from jasper_report_unit_resource_role);
alter sequence jasper_report_unit_resource_id_seq restart with (select coalesce(max(id),0) +1 from jasper_report_unit_resource);
alter sequence tranche_montant_credit_id_seq restart with (select coalesce(max(id),0) +1 from tranche_montant_credit);
alter sequence type_memo_credit_id_seq restart with (select coalesce(max(id),0) +1 from type_memo_credit);
alter sequence dynamic_form_type_pret_id_seq restart with (select coalesce(max(id),0) +1 from dynamic_form_type_pret);
alter sequence taux_epargne_type_pret_id_seq restart with (select coalesce(max(id),0) +1 from taux_epargne_type_pret);
alter sequence taux_epargne_type_pret_cond_client_id_seq restart with (select coalesce(max(id),0) +1 from taux_epargne_type_pret_cond_client);
alter sequence taux_epargne_type_pret_cond_genre_id_seq restart with (select coalesce(max(id),0) +1 from taux_epargne_type_pret_cond_genre);
alter sequence etape_credit_id_seq restart with (select coalesce(max(id),0) +1 from etape_credit);
alter sequence programme_credit_id_seq restart with (select coalesce(max(id),0) +1 from programme_credit);
alter sequence frais_type_pret_cond_client_id_seq restart with (select coalesce(max(id),0) +1 from frais_type_pret_cond_client);
alter sequence frais_type_pret_id_seq restart with (select coalesce(max(id),0) +1 from frais_type_pret);
alter sequence frais_type_pret_cond_genre_id_seq restart with (select coalesce(max(id),0) +1 from frais_type_pret_cond_genre);
alter sequence detail_activite_type_pret_id_seq restart with (select coalesce(max(id),0) +1 from detail_activite_type_pret);
alter sequence nature_bien_id_seq restart with (select coalesce(max(id),0) +1 from nature_bien);
alter sequence compte_type_pret_id_seq restart with (select coalesce(max(id),0) +1 from compte_type_pret);
alter sequence qualite_bien_id_seq restart with (select coalesce(max(id),0) +1 from qualite_bien);
alter sequence taux_provision_id_seq restart with (select coalesce(max(id),0) +1 from taux_provision);
alter sequence type_pret_id_seq restart with (select coalesce(max(id),0) +1 from type_pret);
alter sequence sql_request_id_seq restart with (select coalesce(max(id),0) +1 from sql_request);
alter sequence tranche_de_revenu_id_seq restart with (select coalesce(max(id),0) +1 from tranche_de_revenu);
alter sequence capacite_juridique_id_seq restart with (select coalesce(max(id),0) +1 from capacite_juridique);
alter sequence regime_matrimoniale_id_seq restart with (select coalesce(max(id),0) +1 from regime_matrimoniale);
alter sequence situation_matrimoniale_id_seq restart with (select coalesce(max(id),0) +1 from situation_matrimoniale);

